### ISSUE TITLE
Logo/icon Proposal for Raw-Dumper

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [fkeglevich/Raw-Dumper#2]
Hello,
This my logo/Icon design for your project. It's free for your project.

I design this logo using adobe illustrator cc 2018. I hope you like this logo.

![raw dumper-01](https://user-images.githubusercontent.com/35112507/39071246-27be8940-4508-11e8-8215-d7bbd87a22c1.jpg)

If you need anything change please contact me

Md Nazmul Hasan
Email : nazmul.hasan27771@gmail.com

Thank You.

**Comment by fkeglevich** [comment]
Ok! 
I solicited access to the Google Drive folder
I will update the icon as soon as possible :)

**Comment by mdnazmulhasan27771** [comment]
hi, when you use this logo??

**Comment by fkeglevich** [comment]
Hi,
I solicited access to the Google Drive folder, however, it appears that BitBounce blocked it from appearing on your e-mail, so I still can't download the files.

I'm planning to use the logo when the next version is released, that should happen until the end of the month :)

**Comment by mdnazmulhasan27771** [comment]
please check #3

**Comment by fkeglevich** [comment]
Hi, 
I merged your pull request and now I'm going to replace the icon, post the license and mention your work on the about-box :)

**Comment by mdnazmulhasan27771** [comment]
thank you

**Comment by mdnazmulhasan27771** [comment]
as ur wish

**Comment by fkeglevich** [comment]
Since everything went well, I'm closing this issue

**Comment by TacoTheDank** [comment]
@mdnazmulhasan27771 i understand a bunch of you people are going around trying to contribute to open-source projects to gain some cryptocurrency with utopian.io

unlike any other person i've found (they merely stole icons from flaticons and tried to pass it off as their own, not even caring about the potential legal action it may cause as the icons are under basic licenses), you actually made your own icons, with a professional product, acted quite professional in speech, and i really want to thank you for that. it makes me happy to see people with good values
